Chronische spontane Urtikaria
=============================
= CSU

Therapie
--------
- nach Therapieversuch mit Antihistaminika und bei entsprechendem UAS [[Omalizumab]] 300mg alle 4 Wochen
  - nach 1a bei Beschwerdefreiheit verlängern auf alle 8 Wochen